---
# This playbook will set up development tools required specifically for
# Coreboot 

- name: Install ncurses-dev
  apt: name=libncurses5-dev state=latest
  tags: dev-libraries

- name: Install iasl
  apt: name=iasl state=latest
  tags: compilers