---
# This playbook will setup the ESP8266 development environment

- name: Install Python serial port access module
  apt: name=python-serial state=latest
  tags: python

- name: Install libexpat XML parsing development libraries
  apt: name=libexpat1-dev state=latest
  tags: dev-libraries

  
