---
# This playbook will setup the AVR development environment

- name: Install binutils-avr
  apt: name=binutils-avr state=latest
  tags: AVR

- name: Install gcc-avr cross-compiler
  apt: name=gcc-avr state=latest
  tags: AVR

- name: Install avr-libc
  apt: name=avr-libc state=latest
  tags: AVR

- name: Install gdb-avr debugger
  apt: name=gdb-avr state=latest
  tags: AVR

- name: Install avarice, the AVR In-Ciruit Emulator
  apt: name=avarice state=latest
  tags: AVR

- name: Install avrdude
  apt: name=avrdude state=latest
  tags: AVR

- name: Install avrdude documentation
  apt: name=avrdude-doc state=latest
  tags: AVR

#- name: Install AVR simulator
#  apt: name=simulavr state=latest
#  tags: AVR

- name: Install flashrom
  apt: name=flashrom state=latest
  tags: Embedded

  
  
