---
# download and install vmec

- name: Check if plasma directory exists
  stat: path=/home/vagrant/workspace/vmec
  register: check_path

- name: Check if stellinstall.zip is present
  stat: path=/home/vagrant/workspace/stellinstall.zip
  register: check_stellinstall

- name: result of check if stellinstall.zip exists
  debug: var=check_stellinstall
  
- name: Make directory if doesn't exist
  action: command mkdir /home/vagrant/workspace/vmec
  when: check_path.stat.exists == false

- name: create temporary directory
  command: mktemp -d
  register: tempdir
  
- name: Download md5sum
  get_url: url='http://www.radderacoustics.com/~jerahmie/md5sum.txt' dest={{ tempdir.stdout }}
  
- name: Compare checksums of stellinstall.zip on server with local
  command: vmec_checksum.sh /home/vagrant/workspace/stellinstall.zip {{ tempdir.stdout }}/md5sum.txt
  when: check_stellinstall.stat.exists == true
  register: new_vmec
  
- name: Download VMEC if does not exist
   get_url: url='http://www.radderacoustics.com/~jerahmie/stellinstall.zip' dest=/home/vagrant/workspace owner=vagrant group=vagrant mode=0644
   register: get_vmec
   when: new_vmec == true

 - name: Unzip stellinstall
   command: unzip -qo /home/vagrant/workspace/stellinstall.zip -d /home/vagrant/workspace/vmec
     