---
# download and install vmec

- name: Check if plasma directory exists
  stat: path=/home/vagrant/workspace
  register: check_workspace_path
  
- name: Make workspace directory if doesn't exiust
  file: path=/home/vagrant/workspace state=directory owner=vagrant group=vagrant 
  when: check_workspace_path.stat.exists == false
  
- name: Check if vmec directory exists
  stat: path=/home/vagrant/workspace/vmec
  register: check_vmec_path

- name: Make directory if doesn't exist
  file: path=/home/vagrant/workspace/vmec state=directory owner=vagrant group=vagrant 
  when: check_vmec_path.stat.exists == false

- name: Check if stellinstall.zip is present
  stat: path=/home/vagrant/workspace/stellinstall.zip
  register: check_stellinstall

- name: result of check if stellinstall.zip exists
  debug: var=check_stellinstall
  
- name: create temporary directory
  command: mktemp -d
  register: tempdir
  
- name: Download md5sum
  get_url: url='http://www.radderacoustics.com/~jerahmie/md5sum.txt' dest={{ tempdir.stdout }}
  
- name: Compare checksums of stellinstall.zip on server with local
  command: vmec_checksum.sh /home/vagrant/workspace/stellinstall.zip {{ tempdir.stdout }}/md5sum.txt
  when: check_stellinstall.stat.exists == true
  register: download_vmec

- name: Check status of download_vmec
  debug: download_vmec
  
- name: Download VMEC if does not exist
  get_url: url='http://www.radderacoustics.com/~jerahmie/stellinstall.zip' dest=/home/vagrant/workspace owner=vagrant group=vagrant mode=0644
  register: get_vmec
  when: check_stellinstall.stat.exists == false or download_vmec == true

- name: Check if stellinstall.zip is present
  stat: path=/home/vagrant/workspace/stellinstall.zip
  register: check_stellinstall

- name: Unzip stellinstall
  unarchive: src=/home/vagrant/workspace/stellinstall.zip dest=/home/vagrant/workspace/vmec owner=vagrant group=vagrant
  when: check_stellinstall.stat.exists == true

- name: set vmec dir permissions
  file: /home/vagrant/workspace/vmec state=directory recurse=true owner=vagrant group=vagrant
